"""Central hardware configuration for the fly-behavior box.

Edit these to match your wiring. Everything else reads from here so you never
hunt for a pin number in the middle of a module.
"""

# ---------------------------------------------------------------------------
# Optogenetics — driven via the PCA9685 (same I2C board as illumination).
# ---------------------------------------------------------------------------
# Verified via discovery panel (2026-07-07): PCA9685 ch2 -> RED opto LED,
# ch3 -> BLUE opto LED (the PicoBuck PWM inputs are wired to the PCA9685).
# Pulse trains are generated by software-gating the channel fully ON/OFF, so the
# PCA9685 global frequency stays free for flicker-free strip dimming. The
# PCA9685 duty during "ON" sets LED intensity.
OPTO_CHANNELS = {
    "red": 2,     # PCA9685 ch2 -> PicoBuck -> red Cree LED
    "blue": 3,    # PCA9685 ch3 -> PicoBuck -> blue Cree LED
}
OPTO_MAX_FREQ_HZ = 100     # software-gated pulses; keep modest for timing fidelity
OPTO_DEFAULT_FREQ_HZ = 20
OPTO_DEFAULT_INTENSITY = 1.0   # 0..1, PCA9685 duty used as the "on" level

# ---------------------------------------------------------------------------
# Illumination — PCA9685 (I2C) -> 4-channel MOSFET board -> 12V strips
# ---------------------------------------------------------------------------
PCA9685_I2C_ADDRESS = 0x40   # default; matches the solder-jumper address pads
PCA9685_PWM_FREQ_HZ = 1000   # strips: high enough to be flicker-free on camera
# Map a friendly light name to the PCA9685 output channel that drives the
# corresponding MOSFET input (IN1..IN4).
# Verified empirically via the discovery panel (2026-07-07): white/IR were reversed.
LIGHT_CHANNELS = {
    "white": 1,   # PCA9685 ch1 -> white strip   (was ch0 — swapped after discovery)
    "ir": 0,      # PCA9685 ch0 -> IR strip       (was ch1 — swapped after discovery)
}
# Discovery also found: PCA9685 ch2 -> RED opto LED, ch3 -> BLUE opto LED.
# That means the PicoBuck PWM inputs are driven by the PCA9685, NOT by the Pi's
# GPIO18/19 hardware PWM that opto.py currently assumes. See the routing decision
# before running opto protocols.

# ---------------------------------------------------------------------------
# Camera (picamera2 / IMX477 HQ cam)
# ---------------------------------------------------------------------------
CAMERA_PREVIEW_SIZE = (640, 480)     # low-res MJPEG for the browser preview
CAMERA_RECORD_SIZE = (1920, 1080)    # full-res recording to disk
CAMERA_FPS = 30
RECORDING_DIR = "recordings"         # created under the app folder

# ---------------------------------------------------------------------------
# Web server
# ---------------------------------------------------------------------------
HOST = "0.0.0.0"   # listen on all interfaces (LAN + AP mode)
PORT = 8000
